### ISSUE TITLE
You should never show client Secret of an app

### ISSUE THREAD

**Issue by Cicko** [ww24/github-uploader#1]
There: [link](https://github.com/ww24/github-uploader/blob/30b95d610cecb0951c942e6c0ac3e8d67a592a1d/data/github/oauth.js#L19)

You are showing the client Secret and its very dangerous. You should put it in environment variable to avoid publication of it on internet.

**Comment by ww24** [comment]
Thank you for bringing it to my attention.
I was mistake to publish client secret. I removed its OAuth application and make private this repository.
